controllers/CouponController.php
<?php

namespace app\controllers;

use Yii;
use app\models\Coupon;
use app\models\CouponSearch;
use yii\web\Controller;
use yii\web\NotFoundHttpException;
use yii\filters\VerbFilter;
use yii\db\Query;
use app\modules\kupon\parser\BaseApi as BaseApi;

/**
 * CouponController implements the CRUD actions for Coupon model.
 */
class CouponController extends Controller
{
    public $defaultAction = 'actual';

//    public function behaviors()
//    {
//        return [
//            'verbs' => [
//                'class' => VerbFilter::className(),
//                'actions' => [
//                    'delete' => ['post'],
//                ],
//            ],
//        ];
//    }

    /**
     * Lists all Coupon models.
     * @return mixed
     */
    public function actionActual()
    {
        //echo '<br/><br/><br/><br/>'.Yii::$app->controller->action->id;
        //print_r(Yii::$app->request->queryParams);
        $searchModel = new CouponSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionArchive()
    {
        //echo '<br/><br/><br/><br/>'.Yii::$app->controller->action->id;
        $searchModel = new CouponSearch();
        $dataProvider = $searchModel->search(Yii::$app->request->queryParams);

        return $this->render('index', [
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    /**
     * Displays a single Coupon model.
     * @param integer $id
     * @return mixed
     */
    public function actionView($id)
    {
        $model = $this->findModel($id);

        $api = BaseApi::getApiObject($model->sourceService->id);
        $api->updateCouponById($model->id);

        return $this->render('view', [
            'model' => $this->findModel($id),
        ]);
    }

    /**
     * Creates a new Coupon model.
     * If creation is successful, the browser will be redirected to the 'view' page.
     * @return mixed
     */
//    public function actionCreate()
//    {
//        $model = new Coupon();
//
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        } else {
//            return $this->render('create', [
//                'model' => $model,
//            ]);
//        }
//    }

    /**
     * Updates an existing Coupon model.
     * If update is successful, the browser will be redirected to the 'view' page.
     * @param integer $id
     * @return mixed
     */
//    public function actionUpdate($id)
//    {
//        $model = $this->findModel($id);
//
//        if ($model->load(Yii::$app->request->post()) && $model->save()) {
//            return $this->redirect(['view', 'id' => $model->id]);
//        } else {
//            return $this->render('update', [
//                'model' => $model,
//            ]);
//        }
//    }

    /**
     * Deletes an existing Coupon model.
     * If deletion is successful, the browser will be redirected to the 'index' page.
     * @param integer $id
     * @return mixed
     */
//    public function actionDelete($id)
//    {
//        $this->findModel($id)->delete();
//
//        return $this->redirect(['index']);
//    }

    /**
     * Finds the Coupon model based on its primary key value.
     * If the model is not found, a 404 HTTP exception will be thrown.
     * @param integer $id
     * @return Coupon the loaded model
     * @throws NotFoundHttpException if the model cannot be found
     */
    protected function findModel($id)
    {
        if (($model = Coupon::findOne($id)) !== null) {
            return $model;
        } else {
            throw new NotFoundHttpException('The requested page does not exist.');
        }
    }
}

controllers/SiteController.php
<?php

namespace app\controllers;

use app\models\SourceService;
use app\models\Statistics;
use DateInterval;
use DatePeriod;
use DateTime;
use Yii;
use yii\data\ArrayDataProvider;
use yii\filters\AccessControl;
use yii\web\Controller;
use yii\filters\VerbFilter;
use app\models\LoginForm;
use app\models\ContactForm;

class SiteController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['logout'],
                'rules' => [
                    [
                        'actions' => ['logout'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
            'captcha' => [
                'class' => 'yii\captcha\CaptchaAction',
                'fixedVerifyCode' => YII_ENV_TEST ? 'testme' : null,
            ],
        ];
    }

    public function actionIndex()
    {
        return $this->render('index');
    }

    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->goBack();
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }

    public function actionContact()
    {
        $model = new ContactForm();
        if ($model->load(Yii::$app->request->post()) && $model->contact(Yii::$app->params['adminEmail'])) {
            Yii::$app->session->setFlash('contactFormSubmitted');

            return $this->refresh();
        } else {
            return $this->render('contact', [
                'model' => $model,
            ]);
        }
    }

    public function actionAbout()
    {
        return $this->render('about');
    }

    public function actionReformal()
    {
        return $this->render('reformal');
    }

    public function actionStatistics()
    {
        if (!Yii::$app->request->isAjax) return;
        $currentDay = new DateTime('today');
        $endPeriod = clone $currentDay; //потому что странный пхп меняет исходный объект при присвоении.
        $weekDay = new DateTime('-7 day');
        $weekDays = new DatePeriod($weekDay, new DateInterval('P1D'), $endPeriod->modify('+1 day'));
        $monthDay = new DateTime('-30 day');
        $monthDays = new DatePeriod($monthDay, new DateInterval('P1D'), $endPeriod->modify('+1 day'));
        $data = Statistics::find()->asArray()->all();
        $services = SourceService::find()->select('id, serviceName')->asArray()->all();
        //День
        foreach ($services as $service) {
            $newSum = 0;
            $archiveSum = 0;
            foreach ($data as $i) {
                if ($i['sourceId']===$service['id'] && $i['createDate']===$currentDay->format('Y-m-d')
                    && $i['codeType']==='new'){
                    $newSum += (int)$i['count'];
                }
                if ($i['sourceId']===$service['id'] && $i['createDate']===$currentDay->format('Y-m-d')
                    && $i['codeType']==='archive'){
                    $archiveSum += (int)$i['count'];
                }
            }
            $newDay['new'][$service['serviceName']] = $newSum;
            $newDay['archive'][$service['serviceName']] = $archiveSum;
        }
        //неделя
        foreach ($services as $service) {
            $newSum = 0;
            $archiveSum = 0;
            foreach ($weekDays as $wd) {
                foreach ($data as $i) {
                    if ($i['sourceId'] === $service['id'] && $i['createDate'] === $wd->format('Y-m-d')
                        && $i['codeType']==='new') {
                        $newSum += (int)$i['count'];
                    }
                    if ($i['sourceId'] === $service['id'] && $i['createDate'] === $wd->format('Y-m-d')
                        && $i['codeType']==='archive') {
                        $archiveSum += (int)$i['count'];
                    }
                }
            }
            $newWeek['new'][$service['serviceName']] = $newSum;
            $newWeek['archive'][$service['serviceName']] = $archiveSum;
        }
        //месяц
        foreach ($services as $service) {
            $newSum = 0;
            $archiveSum = 0;
            foreach ($monthDays as $md) {
                foreach ($data as $i) {
                    if ($i['sourceId'] === $service['id'] && $i['createDate'] === $md->format('Y-m-d')
                        && $i['codeType']==='new') {
                        $newSum += (int)$i['count'];
                    }
                    if ($i['sourceId'] === $service['id'] && $i['createDate'] === $md->format('Y-m-d')
                        && $i['codeType']==='archive') {
                        $archiveSum += (int)$i['count'];
                    }
                }
            }
            $newMonth['new'][$service['serviceName']] = $newSum;
            $newMonth['archive'][$service['serviceName']] = $archiveSum;
        }
        foreach ($services as $service) {
            $newArray[] = [
                'name' => $service['serviceName'],
                'today' => isset($newDay['new'][$service['serviceName']])?$newDay['new'][$service['serviceName']]:0,
                'week' => isset($newWeek['new'][$service['serviceName']])?$newWeek['new'][$service['serviceName']]:0,
                'month' => isset($newMonth['new'][$service['serviceName']])?$newMonth['new'][$service['serviceName']]:0,
            ];
            $archiveArray[] = [
                'name' => $service['serviceName'],
                'today' => isset($newDay['archive'][$service['serviceName']])?$newDay['archive'][$service['serviceName']]:0,
                'week' => isset($newWeek['archive'][$service['serviceName']])?$newWeek['archive'][$service['serviceName']]:0,
                'month' => isset($newMonth['archive'][$service['serviceName']])?$newMonth['archive'][$service['serviceName']]:0,
            ];
        }
        $arrayProviderNew = new ArrayDataProvider([
            'allModels' => $newArray,
            'pagination' => [
                'pageSize' => 50,
            ],
        ]);
        $arrayProviderArchived = new ArrayDataProvider([
            'allModels' => $archiveArray,
            'pagination' => [
                'pageSize' => 50,
            ],
        ]);

        return $this->renderPartial('_statistics', ['arrayProviderNew' => $arrayProviderNew,
            'arrayProviderArchived' => $arrayProviderArchived
        ]);
    }
}

views/layouts/main.php
<?php
use yii\helpers\Html;
use yii\bootstrap\Nav;
use yii\bootstrap\NavBar;
use yii\widgets\Breadcrumbs;
use app\assets\AppAsset;

/* @var $this \yii\web\View */
/* @var $content string */

AppAsset::register($this);
?>
<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>

    <META name="description" CONTENT="Skid.KZ - единый агрегатор скидок в Казахстане! Все скидки на одном сайте! Skid.KZ - Архив всех скидок всех городов Казахстана! Более 10000 актуальных и архивных купонов и скидок В Астане, Алмате и других городах Казахстана! Skid.KZ - все актуальные скидки и купоны всех городов Казахстана в одном месте! Более 6000 скидок и купонов! Все купоны с сайтов Chocolife.me, Blizzard.kz, MirKuponov.kz, AutoKupon.kz и других! Все купоны и скидки в городах Алматы, Астана, Актау, Актобе, Атырау, Балхаш, Жезказган, Караганда, Кокшетау, Костанай, Кызылорда, Павлодар, Петропавловск, Рудный, Семей, Талдыкорган, Тараз, Темиртау, Туркестан, Уральск, Усть-Каменогорск, Шымкент, Экибастуз">
    <META name="keywords" CONTENT="купон, все купоны, все скидки Казахстана, все скидки, скидки, агрегатор скидок, поиск скидок, фильтр скидок, база скидок, 
    скидки Алматы,  скидки Астана,  скидки Актау,  скидки Актобе,  скидки Атырау,  скидки Балхаш,  скидки Жезказган,  скидки Караганда,  скидки Кокшетау,  скидки Костанай,  скидки Кызылорда,  скидки Павлодар,  скидки Петропавловск,  скидки Рудный,  скидки Семей,  скидки Талдыкорган,  скидки Тараз,  скидки Темиртау,  скидки Туркестан,  скидки Уральск,  скидки Усть-Каменогорск,  скидки Шымкент,  скидки Экибастуз,
    купоны Алматы,  купоны Астана,  купоны Актау,  купоны Актобе,  купоны Атырау,  купоны Балхаш,  купоны Жезказган,  купоны Караганда,  купоны Кокшетау,  купоны Костанай,  купоны Кызылорда,  купоны Павлодар,  купоны Петропавловск,  купоны Рудный,  купоны Семей,  купоны Талдыкорган,  купоны Тараз,  купоны Темиртау,  купоны Туркестан,  купоны Уральск,  купоны Усть-Каменогорск,  купоны Шымкент,  купоны Экибастуз">

    <meta name='yandex-verification' content='7fb38916fdf8c4ff' />

      <!-- CSS  -->
      <!--<link href="/themes/material-default/css/materialize.css" type="text/css" rel="stylesheet" media="screen,projection"/>-->
      <!--<link href="/themes/material-default/css/style.css" type="text/css" rel="stylesheet" media="screen,projection"/>-->

    <!-- Google Analitycs -->
    <script>
        (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
            (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
            m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
        })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

        ga('create', 'UA-58205853-1', 'auto');
        ga('send', 'pageview');

    </script>

    <!-- Yandex.Metrika counter -->
    <script type="text/javascript">
        (function (d, w, c) {
            (w[c] = w[c] || []).push(function() {
                try {
                    w.yaCounter27811728 = new Ya.Metrika({id:27811728,
                        webvisor:true,
                        clickmap:true,
                        trackLinks:true,
                        accurateTrackBounce:true});
                } catch(e) { }
            });

            var n = d.getElementsByTagName("script")[0],
                s = d.createElement("script"),
                f = function () { n.parentNode.insertBefore(s, n); };
            s.type = "text/javascript";
            s.async = true;
            s.src = (d.location.protocol == "https:" ? "https:" : "http:") + "//mc.yandex.ru/metrika/watch.js";

            if (w.opera == "[object Opera]") {
                d.addEventListener("DOMContentLoaded", f, false);
            } else { f(); }
        })(document, window, "yandex_metrika_callbacks");
    </script>
    <noscript><div><img src="//mc.yandex.ru/watch/27811728" style="position:absolute; left:-9999px;" alt="" /></div></noscript>
    <!-- /Yandex.Metrika counter -->
</head>
<body>

<?php $this->beginBody() ?>
    <div class="wrap">
        <?php
            NavBar::begin([
                'brandLabel' => 'Skid.KZ',
                'brandUrl' => ['/coupon/actual'],
                'options' => [
                    'class' => 'navbar-inverse navbar-fixed-top',
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-left'],
                'items' => [
                    ['label' => 'Актуальные', 'url' => ['/coupon/actual']],
                    ['label' => 'Архив', 'url' => ['/coupon/archive']],
                    ['label' => 'Статистика', 'url' => '#', 'options' => [
                        'data-toggle' => 'modal',
                        'data-target' => '#statModal'
                    ]],
                ],
            ]);
            echo Nav::widget([
                'options' => ['class' => 'navbar-nav navbar-right'],
                'items' => [
                    //['label' => 'Home', 'url' => ['/site/index']],
                    ['label' => 'Отзывы', 'url' => ['/site/reformal']],
                    ['label' => 'О сайте', 'url' => ['/site/about']],
                    //['label' => 'Contact', 'url' => ['/site/contact']],
//                    Yii::$app->user->isGuest ?
//                        ['label' => 'Login', 'url' => ['/site/login']] :
//                        ['label' => 'Logout (' . Yii::$app->user->identity->username . ')',
//                            'url' => ['/site/logout'],
//                            'linkOptions' => ['data-method' => 'post']],
                ],
            ]);
            NavBar::end();
        ?>

        <div class="container">
            <?= Breadcrumbs::widget([
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]) ?>

            <?= $content ?>
            
            <?=Yii::$app->view->render('/site/statistics')?>
            <?php Yii::$app->view->registerJs(<<<JS
                $.ajax({
                        url: "/site/statistics",
                        success: function (data) {
                            $("#statModal .modal-body").append(data);
                        },
                        error: function(jqXHR, textStatus, errorThrown) {
                            console.log(errorThrown);
                        }

                });
JS
                , \yii\web\View::POS_READY);
                ?>
                
            <script async src="//pagead2.googlesyndication.com/pagead/js/adsbygoogle.js"></script>
            <!-- Все мои сервисы -->
            <ins class="adsbygoogle"
                 style="display:block"
                 data-ad-client="ca-pub-7212327600726803"
                 data-ad-slot="3252207281"
                 data-ad-format="auto"></ins>
            <script>
            (adsbygoogle = window.adsbygoogle || []).push({});
            </script>
        </div>
    </div>

    <footer class="footer">
        <div class="container">
            <p class="pull-left">&copy; Skid.KZ, <?= '2014 - ' . date('Y') ?></p>
        </div>
    </footer>

  <!--  Scripts-->
  <!--  <script src="https://code.jquery.com/jquery-2.1.1.min.js"></script>-->
  <!--  <script src="/themes/material-default/js/materialize.js"></script>-->
  <!--  <script src="/themes/material-default/js/init.js"></script>-->

<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>